spring:
  datasource:
    # RDS 접근 설정
    url: ${RDS_END_POINT}
    username: ${RDS_MYSQL_ADMIN_ID}
    password: ${RDS_MYSQL_ADMIN_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URL}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - account_email
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
    show-sql: true

  mail:
    smtp:
      host: smtp.gmail.com
      port: 587
      username: ${EMAIL_USERNAME} # Gmail email
      password: ${EMAIL_PASSWORD} # Google 계정 2단계 인증 생성 후 앱 비밀번호 생성
      auth: true
      starttls:
        enable: true #일부 SMTP 서버에는 TLS 연결이 필요하므로 TLS 보호 연결을 활성화한다
    subject:
      member:
        registration: Thank you for joining our cafe!

  redis:
    cache:
      host: localhost
      port: 6379

jwt:
  key:
    secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 30
  redirect:
    scheme: ${REDIRECT_SCHEME}
    host: ${REDIRECT_HOST}
    port: ${REDIRECT_PORT}
    path: ${REDIRECT_PATH}


logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

cloud:
  aws:
    # S3 접근 권한 설정 -image
    credentials:
      accessKey : ${ACCESS_KEY}
      secretKey : ${SECRET_ACCESS_KEY}
    s3:
      bucket: seb44main028image-bucket
    region:
      static: ap-northeast-2
    stack:
      auto:
        false

kakao:
  restapi : ${KAKAO_REST_API}

category:
  image:
    path: ${CATEGORY.IMAGE.PATH}

image:
  default:
    path: ${IMAGE.DEFAULT.PATH}

